/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas.Modulo_Usuario;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author PC
 */
public class B extends javax.swing.JPanel {

    /**
     * Creates new form B
     */
    public B() {
        initComponents();
        
        final Timer timer = new Timer();
        
        TimerTask task = new TimerTask() 
        {
            public void run() 
            {
                System.out.println("acción acontecida");
                C poper = new C();
                poper.setSize(350,330);
                B.removeAll();
                B.add(poper);
                B.revalidate();
                B.repaint();
                System.out.println("acción acontecida 1");
            }
        };
        timer.schedule(task, 100); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        uno = new javax.swing.JLabel();
        info8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B.setBackground(new java.awt.Color(255, 255, 255));
        B.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Accediendo al servidor");
        B.add(jLabel20);
        jLabel20.setBounds(0, 239, 350, 20);

        uno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uno.setForeground(new java.awt.Color(102, 102, 102));
        uno.setText("              Espere un momento...");
        B.add(uno);
        uno.setBounds(50, 256, 270, 17);

        info8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        info8.setForeground(new java.awt.Color(102, 102, 102));
        info8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cargando-Espere-Por-Favor-62159.gif"))); // NOI18N
        B.add(info8);
        info8.setBounds(0, 139, 350, 120);

        add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 410));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel B;
    public static javax.swing.JLabel info8;
    public static javax.swing.JLabel jLabel20;
    private javax.swing.JLabel uno;
    // End of variables declaration//GEN-END:variables
}
