/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas.Modulo_AcercaDe;

import Alerts.ConexionAlert;
import Ventanas.Inicio.*;
import Ventanas.Modulo_Navegacion.Actualizacion;
import java.net.InetSocketAddress;
import java.net.Socket;

/**
 *
 * @author jvald
 */
public class pnlAcerca extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicio
     */
    public pnlAcerca() {
        initComponents();
    }
    boolean conexion = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        info = new javax.swing.JLabel();
        info1 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();
        info3 = new javax.swing.JLabel();
        log = new JButtonEspecial.JButtonEspecial();
        jLabel6 = new javax.swing.JLabel();

        pnlPrincipal.setBackground(new java.awt.Color(248, 249, 250));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        info.setForeground(new java.awt.Color(102, 102, 102));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cuadro2.PNG"))); // NOI18N
        pnlPrincipal.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 63, -1, 360));

        info1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        info1.setForeground(new java.awt.Color(102, 102, 102));
        info1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info1.setText("PROMEDIC, Todos Los Derechos Reservados ®");
        pnlPrincipal.add(info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 632, 1117, 22));

        info2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        info2.setForeground(new java.awt.Color(102, 102, 102));
        info2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info2.setText("Versión. ");
        pnlPrincipal.add(info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 592, -1, 22));

        info3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        info3.setForeground(new java.awt.Color(102, 102, 102));
        info3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info3.setText("1.0.0.1");
        pnlPrincipal.add(info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 592, -1, 22));

        log.setBackground(new java.awt.Color(204, 204, 204));
        log.setForeground(new java.awt.Color(128, 128, 131));
        log.setText("Buscar Actualización");
        log.setColorHover(new java.awt.Color(204, 204, 204));
        log.setColorNormal(new java.awt.Color(204, 204, 204));
        log.setColorPressed(new java.awt.Color(153, 153, 153));
        log.setColorTextHover(new java.awt.Color(128, 128, 131));
        log.setColorTextNormal(new java.awt.Color(128, 128, 131));
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        pnlPrincipal.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 250, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Información de ProMedic");
        jLabel6.setToolTipText("");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setInheritsPopupMenu(false);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnlPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
            Socket sock = new Socket();
            InetSocketAddress addr = new InetSocketAddress("www.google.com",80);
            try
            {
                sock.connect(addr,3000);
                conexion = true;
                
                    if(conexion == true)
                    {
                        Actualizacion poper = new Actualizacion(null, true);
                        poper.setVisible(true);
                    }
            }
            catch(Exception e)
            {
                conexion = false;
                ConexionAlert poper = new ConexionAlert(null, true);
                poper.setVisible(true);
            }
    }//GEN-LAST:event_logActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel info;
    public static javax.swing.JLabel info1;
    public static javax.swing.JLabel info2;
    public static javax.swing.JLabel info3;
    private javax.swing.JLabel jLabel6;
    private JButtonEspecial.JButtonEspecial log;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
